services:
  postgres:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=paso
    volumes:
      - ./OdooDev/dataPG:/var/lib/postgresql/data
  odoo:
    image: odoo:16
    container_name: odoo_16
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=paso
    ports:
      - '8069:8069'
    volumes:
      - ./OdooDev/volumesOdoo/addons:/mnt/extra-addons
      - ./OdooDev/volumesOdoo/filestore:/var/lib/odoo/filestore
      - ./OdooDev/volumesOdoo/sessions:/var/lib/odoo/sessions
    depends_on:
      - postgres
    command: --dev=all

  postgresprod:
    image: postgres:14
    container_name: dbprod
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=paso
  odooprod:
    image: odoo:16
    container_name: odoo_16_prod
    environment:
      - HOST=postgresprod
      - USER=root
      - PASSWORD=paso
    ports:
      - '8070:8069'
    volumes:
      - ./OdooProd/addons:/mnt/extra-addons
    depends_on:
      - postgresprod

  